"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.adminDataRouter = exports.categoriesRouter = exports.couponsRouter = exports.brandsRouter = exports.ordersRouter = exports.adminRouter = exports.usersRouter = exports.productsRouter = void 0;
const products_1 = __importDefault(require("./products"));
exports.productsRouter = products_1.default;
const users_1 = __importDefault(require("./users"));
exports.usersRouter = users_1.default;
const admin_1 = __importDefault(require("./admin"));
exports.adminRouter = admin_1.default;
const orders_1 = __importDefault(require("./orders"));
exports.ordersRouter = orders_1.default;
const brands_1 = __importDefault(require("./brands"));
exports.brandsRouter = brands_1.default;
const coupons_1 = __importDefault(require("./coupons"));
exports.couponsRouter = coupons_1.default;
const categories_1 = __importDefault(require("./categories"));
exports.categoriesRouter = categories_1.default;
const adminData_1 = __importDefault(require("./adminData"));
exports.adminDataRouter = adminData_1.default;
