"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const ProductsController_1 = __importDefault(require("../http/controllers/ProductsController"));
const checkIsAdmin_1 = require("../middlewares/checkIsAdmin");
const productsRouter = express_1.default.Router();
productsRouter.use(checkIsAdmin_1.checkIsAdmin);
productsRouter.get('/products', ProductsController_1.default.get);
productsRouter.post('/products/create', ProductsController_1.default.createProduct);
productsRouter.get('/products/:id', ProductsController_1.default.getProduct);
productsRouter.get('/products/:id/brand', ProductsController_1.default.getProductBrand);
productsRouter.get('/products/:id/pictures', ProductsController_1.default.getProductPictures);
productsRouter.post('/products/:id/pictures/add', ProductsController_1.default.createProductPicture);
productsRouter.patch('/products/:id/pictures/update/:pictureId', ProductsController_1.default.updateProductPicture);
productsRouter.delete('/products/:id/pictures/delete/:pictureId', ProductsController_1.default.deleteProductPicture);
productsRouter.get('/products/:id/category', ProductsController_1.default.getProductCategory);
productsRouter.patch('/products/:id/update', ProductsController_1.default.updateProduct);
productsRouter.delete('/products/:id/delete', ProductsController_1.default.deleteProduct);
exports.default = productsRouter;
